package wpbn.pgis.entity;

public class Class {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.TYPE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.CLASSES
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String classes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.MACHINES
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Integer machines;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column class.C_ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Integer cId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.ID
	 * @return  the value of class.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.ID
	 * @param id  the value for class.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.TYPE
	 * @return  the value of class.TYPE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.TYPE
	 * @param type  the value for class.TYPE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.CLASSES
	 * @return  the value of class.CLASSES
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getClasses() {
		return classes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.CLASSES
	 * @param classes  the value for class.CLASSES
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setClasses(String classes) {
		this.classes = classes == null ? null : classes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.MACHINES
	 * @return  the value of class.MACHINES
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Integer getMachines() {
		return machines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.MACHINES
	 * @param machines  the value for class.MACHINES
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setMachines(Integer machines) {
		this.machines = machines;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column class.C_ID
	 * @return  the value of class.C_ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Integer getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column class.C_ID
	 * @param cId  the value for class.C_ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setcId(Integer cId) {
		this.cId = cId;
	}
}