package wpbn.pgis.entity;

import java.util.ArrayList;
import java.util.List;

public class ClassExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public ClassExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("TYPE is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(String value) {
			addCriterion("TYPE =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(String value) {
			addCriterion("TYPE <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(String value) {
			addCriterion("TYPE >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TYPE >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(String value) {
			addCriterion("TYPE <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(String value) {
			addCriterion("TYPE <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLike(String value) {
			addCriterion("TYPE like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotLike(String value) {
			addCriterion("TYPE not like", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<String> values) {
			addCriterion("TYPE in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<String> values) {
			addCriterion("TYPE not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(String value1, String value2) {
			addCriterion("TYPE between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(String value1, String value2) {
			addCriterion("TYPE not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andClassesIsNull() {
			addCriterion("CLASSES is null");
			return (Criteria) this;
		}

		public Criteria andClassesIsNotNull() {
			addCriterion("CLASSES is not null");
			return (Criteria) this;
		}

		public Criteria andClassesEqualTo(String value) {
			addCriterion("CLASSES =", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotEqualTo(String value) {
			addCriterion("CLASSES <>", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesGreaterThan(String value) {
			addCriterion("CLASSES >", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesGreaterThanOrEqualTo(String value) {
			addCriterion("CLASSES >=", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesLessThan(String value) {
			addCriterion("CLASSES <", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesLessThanOrEqualTo(String value) {
			addCriterion("CLASSES <=", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesLike(String value) {
			addCriterion("CLASSES like", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotLike(String value) {
			addCriterion("CLASSES not like", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesIn(List<String> values) {
			addCriterion("CLASSES in", values, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotIn(List<String> values) {
			addCriterion("CLASSES not in", values, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesBetween(String value1, String value2) {
			addCriterion("CLASSES between", value1, value2, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotBetween(String value1, String value2) {
			addCriterion("CLASSES not between", value1, value2, "classes");
			return (Criteria) this;
		}

		public Criteria andMachinesIsNull() {
			addCriterion("MACHINES is null");
			return (Criteria) this;
		}

		public Criteria andMachinesIsNotNull() {
			addCriterion("MACHINES is not null");
			return (Criteria) this;
		}

		public Criteria andMachinesEqualTo(Integer value) {
			addCriterion("MACHINES =", value, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesNotEqualTo(Integer value) {
			addCriterion("MACHINES <>", value, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesGreaterThan(Integer value) {
			addCriterion("MACHINES >", value, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesGreaterThanOrEqualTo(Integer value) {
			addCriterion("MACHINES >=", value, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesLessThan(Integer value) {
			addCriterion("MACHINES <", value, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesLessThanOrEqualTo(Integer value) {
			addCriterion("MACHINES <=", value, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesIn(List<Integer> values) {
			addCriterion("MACHINES in", values, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesNotIn(List<Integer> values) {
			addCriterion("MACHINES not in", values, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesBetween(Integer value1, Integer value2) {
			addCriterion("MACHINES between", value1, value2, "machines");
			return (Criteria) this;
		}

		public Criteria andMachinesNotBetween(Integer value1, Integer value2) {
			addCriterion("MACHINES not between", value1, value2, "machines");
			return (Criteria) this;
		}

		public Criteria andCIdIsNull() {
			addCriterion("C_ID is null");
			return (Criteria) this;
		}

		public Criteria andCIdIsNotNull() {
			addCriterion("C_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCIdEqualTo(Integer value) {
			addCriterion("C_ID =", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotEqualTo(Integer value) {
			addCriterion("C_ID <>", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThan(Integer value) {
			addCriterion("C_ID >", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("C_ID >=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThan(Integer value) {
			addCriterion("C_ID <", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThanOrEqualTo(Integer value) {
			addCriterion("C_ID <=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdIn(List<Integer> values) {
			addCriterion("C_ID in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotIn(List<Integer> values) {
			addCriterion("C_ID not in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdBetween(Integer value1, Integer value2) {
			addCriterion("C_ID between", value1, value2, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotBetween(Integer value1, Integer value2) {
			addCriterion("C_ID not between", value1, value2, "cId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table class
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table class
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 17 10:34:27 IST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}