package wpbn.pgis.entity;

import java.util.Date;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.CODE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.TITLE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.DURATION
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Date duration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.START_DATE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column course.END_DATE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Date endDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.ID
	 * @return  the value of course.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.ID
	 * @param id  the value for course.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.CODE
	 * @return  the value of course.CODE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.CODE
	 * @param code  the value for course.CODE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setCode(String code) {
		this.code = code == null ? null : code.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.TITLE
	 * @return  the value of course.TITLE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.TITLE
	 * @param title  the value for course.TITLE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.DURATION
	 * @return  the value of course.DURATION
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Date getDuration() {
		return duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.DURATION
	 * @param duration  the value for course.DURATION
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setDuration(Date duration) {
		this.duration = duration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.START_DATE
	 * @return  the value of course.START_DATE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.START_DATE
	 * @param startDate  the value for course.START_DATE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column course.END_DATE
	 * @return  the value of course.END_DATE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column course.END_DATE
	 * @param endDate  the value for course.END_DATE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
}