package wpbn.pgis.entity;

public class Instructor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.NIC
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String nic;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.NAME
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.ADDRESS
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.EMAIL
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.TELEPHONE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private String telephone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column instructor.C_ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	private Integer cId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.ID
	 * @return  the value of instructor.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.ID
	 * @param id  the value for instructor.ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.NIC
	 * @return  the value of instructor.NIC
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getNic() {
		return nic;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.NIC
	 * @param nic  the value for instructor.NIC
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setNic(String nic) {
		this.nic = nic == null ? null : nic.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.NAME
	 * @return  the value of instructor.NAME
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.NAME
	 * @param name  the value for instructor.NAME
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.ADDRESS
	 * @return  the value of instructor.ADDRESS
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.ADDRESS
	 * @param address  the value for instructor.ADDRESS
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.EMAIL
	 * @return  the value of instructor.EMAIL
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.EMAIL
	 * @param email  the value for instructor.EMAIL
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.TELEPHONE
	 * @return  the value of instructor.TELEPHONE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.TELEPHONE
	 * @param telephone  the value for instructor.TELEPHONE
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column instructor.C_ID
	 * @return  the value of instructor.C_ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public Integer getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column instructor.C_ID
	 * @param cId  the value for instructor.C_ID
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	public void setcId(Integer cId) {
		this.cId = cId;
	}
}