package wpbn.pgis.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class StudentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public StudentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andFnameIsNull() {
			addCriterion("FNAME is null");
			return (Criteria) this;
		}

		public Criteria andFnameIsNotNull() {
			addCriterion("FNAME is not null");
			return (Criteria) this;
		}

		public Criteria andFnameEqualTo(String value) {
			addCriterion("FNAME =", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameNotEqualTo(String value) {
			addCriterion("FNAME <>", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameGreaterThan(String value) {
			addCriterion("FNAME >", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameGreaterThanOrEqualTo(String value) {
			addCriterion("FNAME >=", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameLessThan(String value) {
			addCriterion("FNAME <", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameLessThanOrEqualTo(String value) {
			addCriterion("FNAME <=", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameLike(String value) {
			addCriterion("FNAME like", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameNotLike(String value) {
			addCriterion("FNAME not like", value, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameIn(List<String> values) {
			addCriterion("FNAME in", values, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameNotIn(List<String> values) {
			addCriterion("FNAME not in", values, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameBetween(String value1, String value2) {
			addCriterion("FNAME between", value1, value2, "fname");
			return (Criteria) this;
		}

		public Criteria andFnameNotBetween(String value1, String value2) {
			addCriterion("FNAME not between", value1, value2, "fname");
			return (Criteria) this;
		}

		public Criteria andLnameIsNull() {
			addCriterion("LNAME is null");
			return (Criteria) this;
		}

		public Criteria andLnameIsNotNull() {
			addCriterion("LNAME is not null");
			return (Criteria) this;
		}

		public Criteria andLnameEqualTo(String value) {
			addCriterion("LNAME =", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameNotEqualTo(String value) {
			addCriterion("LNAME <>", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameGreaterThan(String value) {
			addCriterion("LNAME >", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameGreaterThanOrEqualTo(String value) {
			addCriterion("LNAME >=", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameLessThan(String value) {
			addCriterion("LNAME <", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameLessThanOrEqualTo(String value) {
			addCriterion("LNAME <=", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameLike(String value) {
			addCriterion("LNAME like", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameNotLike(String value) {
			addCriterion("LNAME not like", value, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameIn(List<String> values) {
			addCriterion("LNAME in", values, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameNotIn(List<String> values) {
			addCriterion("LNAME not in", values, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameBetween(String value1, String value2) {
			addCriterion("LNAME between", value1, value2, "lname");
			return (Criteria) this;
		}

		public Criteria andLnameNotBetween(String value1, String value2) {
			addCriterion("LNAME not between", value1, value2, "lname");
			return (Criteria) this;
		}

		public Criteria andOtherNamesIsNull() {
			addCriterion("OTHER_NAMES is null");
			return (Criteria) this;
		}

		public Criteria andOtherNamesIsNotNull() {
			addCriterion("OTHER_NAMES is not null");
			return (Criteria) this;
		}

		public Criteria andOtherNamesEqualTo(String value) {
			addCriterion("OTHER_NAMES =", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesNotEqualTo(String value) {
			addCriterion("OTHER_NAMES <>", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesGreaterThan(String value) {
			addCriterion("OTHER_NAMES >", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesGreaterThanOrEqualTo(String value) {
			addCriterion("OTHER_NAMES >=", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesLessThan(String value) {
			addCriterion("OTHER_NAMES <", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesLessThanOrEqualTo(String value) {
			addCriterion("OTHER_NAMES <=", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesLike(String value) {
			addCriterion("OTHER_NAMES like", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesNotLike(String value) {
			addCriterion("OTHER_NAMES not like", value, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesIn(List<String> values) {
			addCriterion("OTHER_NAMES in", values, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesNotIn(List<String> values) {
			addCriterion("OTHER_NAMES not in", values, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesBetween(String value1, String value2) {
			addCriterion("OTHER_NAMES between", value1, value2, "otherNames");
			return (Criteria) this;
		}

		public Criteria andOtherNamesNotBetween(String value1, String value2) {
			addCriterion("OTHER_NAMES not between", value1, value2, "otherNames");
			return (Criteria) this;
		}

		public Criteria andNicIsNull() {
			addCriterion("NIC is null");
			return (Criteria) this;
		}

		public Criteria andNicIsNotNull() {
			addCriterion("NIC is not null");
			return (Criteria) this;
		}

		public Criteria andNicEqualTo(String value) {
			addCriterion("NIC =", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicNotEqualTo(String value) {
			addCriterion("NIC <>", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicGreaterThan(String value) {
			addCriterion("NIC >", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicGreaterThanOrEqualTo(String value) {
			addCriterion("NIC >=", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicLessThan(String value) {
			addCriterion("NIC <", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicLessThanOrEqualTo(String value) {
			addCriterion("NIC <=", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicLike(String value) {
			addCriterion("NIC like", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicNotLike(String value) {
			addCriterion("NIC not like", value, "nic");
			return (Criteria) this;
		}

		public Criteria andNicIn(List<String> values) {
			addCriterion("NIC in", values, "nic");
			return (Criteria) this;
		}

		public Criteria andNicNotIn(List<String> values) {
			addCriterion("NIC not in", values, "nic");
			return (Criteria) this;
		}

		public Criteria andNicBetween(String value1, String value2) {
			addCriterion("NIC between", value1, value2, "nic");
			return (Criteria) this;
		}

		public Criteria andNicNotBetween(String value1, String value2) {
			addCriterion("NIC not between", value1, value2, "nic");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("ADDRESS is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("ADDRESS is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("ADDRESS =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("ADDRESS <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("ADDRESS >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("ADDRESS >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("ADDRESS <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("ADDRESS <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("ADDRESS like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("ADDRESS not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("ADDRESS in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("ADDRESS not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("ADDRESS between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("ADDRESS not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andDobIsNull() {
			addCriterion("DOB is null");
			return (Criteria) this;
		}

		public Criteria andDobIsNotNull() {
			addCriterion("DOB is not null");
			return (Criteria) this;
		}

		public Criteria andDobEqualTo(String value) {
			addCriterion("DOB =", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotEqualTo(String value) {
			addCriterion("DOB <>", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobGreaterThan(String value) {
			addCriterion("DOB >", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobGreaterThanOrEqualTo(String value) {
			addCriterion("DOB >=", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobLessThan(String value) {
			addCriterion("DOB <", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobLessThanOrEqualTo(String value) {
			addCriterion("DOB <=", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobLike(String value) {
			addCriterion("DOB like", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotLike(String value) {
			addCriterion("DOB not like", value, "dob");
			return (Criteria) this;
		}

		public Criteria andDobIn(List<String> values) {
			addCriterion("DOB in", values, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotIn(List<String> values) {
			addCriterion("DOB not in", values, "dob");
			return (Criteria) this;
		}

		public Criteria andDobBetween(String value1, String value2) {
			addCriterion("DOB between", value1, value2, "dob");
			return (Criteria) this;
		}

		public Criteria andDobNotBetween(String value1, String value2) {
			addCriterion("DOB not between", value1, value2, "dob");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("GENDER is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("GENDER is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(String value) {
			addCriterion("GENDER =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(String value) {
			addCriterion("GENDER <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(String value) {
			addCriterion("GENDER >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(String value) {
			addCriterion("GENDER >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(String value) {
			addCriterion("GENDER <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(String value) {
			addCriterion("GENDER <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLike(String value) {
			addCriterion("GENDER like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotLike(String value) {
			addCriterion("GENDER not like", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<String> values) {
			addCriterion("GENDER in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<String> values) {
			addCriterion("GENDER not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(String value1, String value2) {
			addCriterion("GENDER between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(String value1, String value2) {
			addCriterion("GENDER not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNull() {
			addCriterion("TELEPHONE is null");
			return (Criteria) this;
		}

		public Criteria andTelephoneIsNotNull() {
			addCriterion("TELEPHONE is not null");
			return (Criteria) this;
		}

		public Criteria andTelephoneEqualTo(Integer value) {
			addCriterion("TELEPHONE =", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotEqualTo(Integer value) {
			addCriterion("TELEPHONE <>", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThan(Integer value) {
			addCriterion("TELEPHONE >", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneGreaterThanOrEqualTo(Integer value) {
			addCriterion("TELEPHONE >=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThan(Integer value) {
			addCriterion("TELEPHONE <", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneLessThanOrEqualTo(Integer value) {
			addCriterion("TELEPHONE <=", value, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneIn(List<Integer> values) {
			addCriterion("TELEPHONE in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotIn(List<Integer> values) {
			addCriterion("TELEPHONE not in", values, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneBetween(Integer value1, Integer value2) {
			addCriterion("TELEPHONE between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andTelephoneNotBetween(Integer value1, Integer value2) {
			addCriterion("TELEPHONE not between", value1, value2, "telephone");
			return (Criteria) this;
		}

		public Criteria andSchoolIsNull() {
			addCriterion("SCHOOL is null");
			return (Criteria) this;
		}

		public Criteria andSchoolIsNotNull() {
			addCriterion("SCHOOL is not null");
			return (Criteria) this;
		}

		public Criteria andSchoolEqualTo(String value) {
			addCriterion("SCHOOL =", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotEqualTo(String value) {
			addCriterion("SCHOOL <>", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolGreaterThan(String value) {
			addCriterion("SCHOOL >", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolGreaterThanOrEqualTo(String value) {
			addCriterion("SCHOOL >=", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolLessThan(String value) {
			addCriterion("SCHOOL <", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolLessThanOrEqualTo(String value) {
			addCriterion("SCHOOL <=", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolLike(String value) {
			addCriterion("SCHOOL like", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotLike(String value) {
			addCriterion("SCHOOL not like", value, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolIn(List<String> values) {
			addCriterion("SCHOOL in", values, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotIn(List<String> values) {
			addCriterion("SCHOOL not in", values, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolBetween(String value1, String value2) {
			addCriterion("SCHOOL between", value1, value2, "school");
			return (Criteria) this;
		}

		public Criteria andSchoolNotBetween(String value1, String value2) {
			addCriterion("SCHOOL not between", value1, value2, "school");
			return (Criteria) this;
		}

		public Criteria andCIdIsNull() {
			addCriterion("C_ID is null");
			return (Criteria) this;
		}

		public Criteria andCIdIsNotNull() {
			addCriterion("C_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCIdEqualTo(Integer value) {
			addCriterion("C_ID =", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotEqualTo(Integer value) {
			addCriterion("C_ID <>", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThan(Integer value) {
			addCriterion("C_ID >", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("C_ID >=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThan(Integer value) {
			addCriterion("C_ID <", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdLessThanOrEqualTo(Integer value) {
			addCriterion("C_ID <=", value, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdIn(List<Integer> values) {
			addCriterion("C_ID in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotIn(List<Integer> values) {
			addCriterion("C_ID not in", values, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdBetween(Integer value1, Integer value2) {
			addCriterion("C_ID between", value1, value2, "cId");
			return (Criteria) this;
		}

		public Criteria andCIdNotBetween(Integer value1, Integer value2) {
			addCriterion("C_ID not between", value1, value2, "cId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated do_not_delete_during_merge Sat Jun 17 10:34:27 IST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}