package wpbn.pgis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import wpbn.pgis.entity.Course;
import wpbn.pgis.entity.CourseExample;

public interface CourseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	long countByExample(CourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int deleteByExample(CourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int insert(Course record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int insertSelective(Course record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	List<Course> selectByExample(CourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	Course selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int updateByExampleSelective(@Param("record") Course record, @Param("example") CourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int updateByExample(@Param("record") Course record, @Param("example") CourseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int updateByPrimaryKeySelective(Course record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table course
	 * @mbg.generated  Wed Jun 28 12:55:56 IST 2017
	 */
	int updateByPrimaryKey(Course record);

	@Select("SELECT * FROM course")
	@ResultMap(value = "BaseResultMap")
	List<Course> selectAll();

	@Select("SELECT * FROM student WHERE ID= #{id}")
	@ResultMap(value = "BaseResultMap")
	Course findById(@Param("id") String id);
}