package wpbn.pgis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import wpbn.pgis.entity.Instructor;
import wpbn.pgis.entity.InstructorExample;

public interface InstructorMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	long countByExample(InstructorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int deleteByExample(InstructorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int insert(Instructor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int insertSelective(Instructor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	List<Instructor> selectByExample(InstructorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	Instructor selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int updateByExampleSelective(@Param("record") Instructor record, @Param("example") InstructorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int updateByExample(@Param("record") Instructor record, @Param("example") InstructorExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int updateByPrimaryKeySelective(Instructor record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table instructor
	 * @mbg.generated  Mon Jun 26 19:00:37 IST 2017
	 */
	int updateByPrimaryKey(Instructor record);
}