package wpbn.pgis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;

import wpbn.pgis.entity.Student;
import wpbn.pgis.entity.StudentExample;

public interface StudentMapper {

	
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	long countByExample(StudentExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int deleteByExample(StudentExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int deleteByPrimaryKey(Integer id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int insert(Student record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int insertSelective(Student record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	List<Student> selectByExample(StudentExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	Student selectByPrimaryKey(Integer id);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int updateByPrimaryKeySelective(Student record);


	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Wed Jun 28 10:58:14 IST 2017
	 */
	int updateByPrimaryKey(Student record);



	
	@Select("SELECT * FROM student")
	@ResultMap(value = "BaseResultMap")
	List<Student> selectAll();


	@Select("SELECT * FROM student WHERE ID= #{id}")
	@ResultMap(value = "BaseResultMap")
	Student findById(@Param("id") String id);

	
}